### PR TITLE
Add LandSeaMask type

### PR DESCRIPTION
**Pull request by willtebbutt**
As discussed in #14 , this adds some encapsulation to the land-sea mask data and provides an `is_land` function. One question I have is whether this is the correct / most intuitive way to implement the `is_land` function / whether there are better options available.

Once we've agreed on the basics, I'll add some tests and bump the patch version (this isn't breaking) so that we can get a release out.

### CODE REVIEW

**Comment by Alexander-Barth** [comment]
Very nice! Thanks. This looks great to me.

**Comment by willtebbutt** [comment]
Great. I'll do the stuff I mentioned today / tomorrow and ask for another round of review once that's done.

**Comment by willtebbutt** [comment]
@Alexander-Barth ready for review

**Comment by Alexander-Barth** [comment]
Thanks you very much!

**Pull request merged**
